### PR TITLE
Creation of LICENSE file to add a license

### PR DESCRIPTION
**Pull request by s-a-m**
By default, any creative work without an explicit license, including Github repositories like yours, have the most restrictive license of them all: exclusive "all rights reserved" copyright. I assume that since you have your (awesome) software in a Github repository, it is your intent for people to use it, fork it and improve it. Thus, I'd strongly advise to add an open source license to facilitate this -- otherwise, it would be illegal to use this code in any way. If you want to allow any use of it, I'd recommend a MIT License (which is the one I'm including in this pull-request). I am happy to help clarify doubts or uncertainties around all this, or help choose another license if you don't like these (there are other options in Github's https://choosealicense.com).

### CODE REVIEW

**Comment by s-a-m** [comment]
Btw, awesome patch for NOS, works smoothly

**Comment by LukeSkyD** [comment]
Hi, thanks for the suggestion, I would like to implement a license but i would need some help.

I would like
- to be noticed when people use this module for their projects
- their projects to be open source

I don't want my module and/or my name to be shipped with malicious unreachable code.
Is [GNU AGPLv3](https://choosealicense.com/licenses/agpl-3.0/) the best for my situation?

**Comment by s-a-m** [comment]
Happy to help. On the compulsory notification when using this, I'm afraid that's not possible, since that would make the software not free/open sourced. There is [a longer explanation here](https://opensource.stackexchange.com/questions/6963/can-i-modify-an-open-source-license-to-require-that-i-be-notified), but basically users have the right to use your software locally without notifying you. However, you can make compulsory that they release their modifications to your software. You can also make compulsory that they release those modifications as open source. Both the [GPLv3 ](https://choosealicense.com/licenses/gpl-3.0/)and the [AGPLv3](https://choosealicense.com/licenses/agpl-3.0/) would comply with this. AGPL makes sure that the modifications are released even when used in a web service though, so if you want that, yes, that would be the most appropriate license. 

PS: Btw, users that want to play with this, would typically fork your project. And within Github you can see the forks done to your project.

**Comment by LukeSkyD** [comment]
Perfect thank you.

I've created a new branch called license with LICENSE.md and modified service.sh to include a comment with the license reminder

other files were left as they were. everything's ok now right? i can merge

**Comment by s-a-m** [comment]
Yep. If it worked properly, Github will recognize the license and include it in the project summary. You can also use https://choosealicense.com/licenses/agpl-3.0/ and include the github project url on the field, to do it automatically.

**Comment by LukeSkyD** [comment]
Perfect, done.

Thanks again for the great help.

I'll leave this pull request open for a day if something else is needed.

**Comment by s-a-m** [comment]
Awesome, nothing else from my side. Thanks for the acknowledgements.

**Pull request closed without merging**
